### ISSUE TITLE
Won't direct to Facebook sign on page upon login and sign up

### ISSUE THREAD

**Issue by sholdencorbett** [sunsheeppoplar/live-musically-rails#47]
#35 

Notification on login page: We're sorry, but something went wrong.  If you are the application owner check the logs for more information. 

Notification on sign up page: This site can't be reached. localhost refused to connect

**Comment by sunsheeppoplar** [comment]
Checked it on Chrome - good to go on my end

**Comment by sholdencorbett** [comment]
Need to authorize Morganne and me to use Facebook while in test/development mode.

**Comment by sholdencorbett** [comment]
I was able to accept the request on Facebook for Developers, but am now getting an error in staging.

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."
