### ISSUE TITLE
Validation That Promotions Are Only Applied to Yearly Customer Stripe Subscriptions

### ISSUE THREAD

**Issue by sunsheeppoplar** [sunsheeppoplar/live-musically-rails#50]
~~- [ ] hide promotional code input unless clicked on~~

**Comment by sholdencorbett** [comment]
We also need to find a shorter naming convention so that people can easily type in the code rather than having to copy and paste it.  Ideally, we shorten it to five or six characters.  Let's think on this.

**Comment by sholdencorbett** [comment]
$10.00 off for 3 months only discounts $10 for the entire year, instead of $30. The total charged is currently $90 instead of $70.

**Comment by sunsheeppoplar** [comment]
> $10.00 off for 3 months only discounts $10 for the entire year, instead of $30. The total charged is currently $90 instead of $70.

Known issue. Deprecating old coupon on Stripe that was initially used as we were figuring out how they worked.
