### ISSUE TITLE
Hide Promotional Code Input Unless Clicked On

### ISSUE THREAD

**Issue by sunsheeppoplar** [sunsheeppoplar/live-musically-rails#53]
moved from #50

**Comment by sholdencorbett** [comment]
Looks good! The only question I have is do we add the ability to rehide the box if clicked on again?  Or is the box always visible once initially clicked?

**Comment by sunsheeppoplar** [comment]
Up to you. I figure if they click on it then it's just there and if they don't have a code to use that that's fine

**Comment by sholdencorbett** [comment]
Let's keep it how it is.  Thanks!
