### ISSUE TITLE
Profile Picture Cropper Should Update Image In Profile

### ISSUE THREAD

**Issue by sunsheeppoplar** [sunsheeppoplar/live-musically-rails#63]
As it currently stands, you would have to refresh the page to be able to see the results of your cropping. Need to swap out the current picture (if there is one) to the cropped photo. Note, it doesn't get saved until you submit the form still, which seems to be standard behavior.

**Comment by sholdencorbett** [comment]
Profile photo imports and saves sideways (rotated 90% counterclockwise).

**Comment by sunsheeppoplar** [comment]
Seems like this is a bigger issue than just within the app:

https://www.mandolincafe.com/forum/entry.php?713

Gonna close this issue for now. Maybe we could have a rotation feature down the road.
